UPDATE TB_DADO_FUNCIONARIO
SET NM_NOME = 'Josias' WHERE ID = 5;

UPDATE TB_DADO_DO_FUNCIONARIO_PCD
SET DT_NASCIMENTO = '1998-05-12' WHERE ID = 2;

UPDATE TB_ENDERECO
SET NM_BAIRRO = 'BAIRRO 5' WHERE ID = 3;