CREATE TABLE TB_DADO_DO_CANDIDATO(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NM_NOME VARCHAR(100) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    NM_CPF VARCHAR(14) NOT NULL,
    NM_RG VARCHAR(12) NOT NULL
);

CREATE TABLE TB_DADO_FUNCIONARIO(
	ID INT,
	NM_NOME VARCHAR(100) NOT NULL,
    DT_NASC DATE NOT NULL,
    NM_CPF CHAR(14) NOT NULL,
    NM_RG VARCHAR(12) NOT NULL,
    IC_SEXO CHAR(1) NOT NULL,
    PRIMARY KEY (ID),
    CHECK (IC_SEXO in ('M', 'F'))
);

CREATE TABLE TB_AFASTADO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	DS_MOTIVO BLOB,
    DT_DIAS_AFASTADO DATE
);

CREATE TABLE TB_DADO_DO_FUNCIONARIO_PCD(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NM_NOME VARCHAR(100) NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	NM_CPF VARCHAR (14) NOT NULL,
	NM_RG VARCHAR(12) NOT NULL,
	NM_PORTADOR_PCD BLOB NOT NULL
);

CREATE TABLE TB_ADVERTENCIA(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_FUNCIONARIO INT,
    DS_MOTIVOS BLOB NOT NULL,
    DT_DATA DATE NOT NULL,
    FOREIGN KEY (ID_DADO_FUNCIONARIO) REFERENCES TB_DADO_FUNCIONARIO (ID)
);


CREATE TABLE TB_ENDERECO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_FUNCIONARIO INT,
    CD_CEP VARCHAR(11) NOT NULL,
    NM_LOGRADOURO VARCHAR(100) NOT NULL,
    CD_NUMERO INT NOT NULL,
    NM_BAIRRO VARCHAR(50) NOT NULL,
    NM_CIDADE VARCHAR(50) NOT NULL,
    NM_UF VARCHAR(2) NOT NULL,
    FOREIGN KEY (ID_DADO_FUNCIONARIO) REFERENCES TB_DADO_FUNCIONARIO (ID)
);

CREATE TABLE TB_CONTRATO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_FUNCIONARIO INT,
    ID_DADO_DO_FUNCIONARIO_PCD INT,
    NM_CARGO VARCHAR(100) NOT NULL,
    DT_INICIO DATE NOT NULL,
    DT_FIM DATE,
    FOREIGN KEY (ID_DADO_FUNCIONARIO) REFERENCES TB_DADO_FUNCIONARIO (ID),
    FOREIGN KEY (ID_DADO_DO_FUNCIONARIO_PCD) REFERENCES TB_DADO_DO_FUNCIONARIO_PCD (ID)
);

CREATE TABLE TB_PROCESSO_SELETIVO_INTERNO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_FUNCIONARIO INT,
    ID_CONTRATO INT,
    NM_CARGO_PROCESSO VARCHAR(100) NOT NULL,
    DT_CONTRIBUICAO DATE NOT NULL,
    FOREIGN KEY (ID_DADO_FUNCIONARIO) REFERENCES TB_DADO_FUNCIONARIO (ID),
    FOREIGN KEY (ID_CONTRATO) REFERENCES TB_CONTRATO (ID)
);

CREATE TABLE TB_BENEFICIO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_FUNCIONARIO INT,
	VL_VT DECIMAL(5,2) NOT NULL,
	IC_POSSUI_VT CHAR(1) NOT NULL,
	VL_VR DECIMAL(5,2) NOT NULL,
    IC_POSSUI_VR CHAR(1) NOT NULL,
    VL_AUX_MEDICO DECIMAL(5,2) NOT NULL,
    IC_POSSUI_AUXM CHAR(1) NOT NULL,
    FOREIGN KEY (ID_DADO_FUNCIONARIO) REFERENCES TB_DADO_FUNCIONARIO (ID)
);

CREATE TABLE TB_DEMISSAO(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    	ID_CONTRATO INT,
	IC_JC CHAR(1) NOT NULL,
	DT_DEMISSAO DATETIME NOT NULL,
	DS_MOTIVOS BLOB NOT NULL,
    FOREIGN KEY (ID_CONTRATO) REFERENCES TB_CONTRATO (ID)
);

CREATE TABLE TB_FOLHA_PONTO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_CONTRATO INT,
    DT_CARGA_HORARIA DATETIME NOT NULL,
    DT_ATRASOS DATETIME,
    FOREIGN KEY (ID_CONTRATO) REFERENCES TB_CONTRATO (ID)
);

CREATE TABLE TB_SALARIO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_BENEFICIO INT,
    ID_CONTRATO INT,
    ID_FOLHA_PONTO INT,
    VL_DESC_PONTO DECIMAL(8,2),
    VL_DESC_BENEF DECIMAL(8,2),
    VL_VALOR_SAL DECIMAL(8,2) NOT NULL,
    FOREIGN KEY (ID_BENEFICIO) REFERENCES TB_BENEFICIO (ID),
    FOREIGN KEY (ID_CONTRATO) REFERENCES TB_CONTRATO (ID),
    FOREIGN KEY (ID_FOLHA_PONTO) REFERENCES TB_FOLHA_PONTO (ID)
);

CREATE TABLE TB_CURRICULO(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    	ID_DADO_DO_CANDIDATO INT,
	DS_EXPERIENCIAS_PROFISSIONAIS BLOB NOT NULL,
	DT_ENVIO DATETIME,
    	FOREIGN KEY (ID_DADO_DO_CANDIDATO) REFERENCES TB_DADO_DO_CANDIDATO (ID)
);

CREATE TABLE TB_FERIAS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_CONTRATO INT,
    ID_FOLHA_PONTO INT,
    ID_DADO_FUNCIONARIO INT,
    DT_RETORNO DATE NOT NULL,
    FOREIGN KEY (ID_CONTRATO) REFERENCES TB_CONTRATO (ID),
    FOREIGN KEY (ID_FOLHA_PONTO) REFERENCES TB_FOLHA_PONTO (ID),
    FOREIGN KEY (ID_DADO_FUNCIONARIO) REFERENCES TB_DADO_FUNCIONARIO (ID)
);

CREATE TABLE TB_PROCESSO_SELETIVO_EXTERNO(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_CANDIDATO INT,
	NM_CARGO VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_DADO_CANDIDATO) REFERENCES TB_DADO_DO_CANDIDATO (ID)
);

CREATE TABLE TB_ATESTADO (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_FUNCIONARIO INT,
    ID_FOLHA_PONTO INT,
    ID_AFASTADO INT,
    DT_ATESTADO DATE ,
    DS_MOTIVO BLOB,
    FOREIGN KEY (ID_DADO_FUNCIONARIO) REFERENCES TB_DADO_FUNCIONARIO (ID),
    FOREIGN KEY (ID_FOLHA_PONTO) REFERENCES TB_FOLHA_PONTO (ID),
    FOREIGN KEY (ID_AFASTADO) REFERENCES TB_AFASTADO (ID)
);

CREATE TABLE TB_CHAMADO_TI(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_FUNCIONARIO INT,
	DS_MOTIVO BLOB NOT NULL,
	DT_HORA DATETIME NOT NULL,
	IC_RESOLVIDO CHAR(1) NOT NULL,
    FOREIGN KEY (ID_DADO_FUNCIONARIO) REFERENCES TB_DADO_FUNCIONARIO (ID)
);

CREATE TABLE TB_SEGURANCA_TRABALHO(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_FUNCIONARIO INT,
	DS_MOTIVO BLOB NOT NULL,
	DT_HORA DATETIME NOT NULL,
	IC_RESOLVIDO CHAR(1) NOT NULL,
    FOREIGN KEY (ID_DADO_FUNCIONARIO) REFERENCES TB_DADO_FUNCIONARIO (ID)
);

CREATE TABLE TB_STAND_BY(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_CANDIDATO INT,
    DS_MOTIVOS BLOB NOT NULL,
    FOREIGN KEY (ID_DADO_CANDIDATO) REFERENCES TB_DADO_DO_CANDIDATO (ID)
);

CREATE TABLE TB_PRESTACAO_CONTAS_FUNCIONARIO(
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_DADO_FUNCIONARIO INT,
    DS_FISCALIZACAO BLOB NOT NULL,
    FOREIGN KEY (ID_DADO_FUNCIONARIO) REFERENCES TB_DADO_FUNCIONARIO (ID)
);

CREATE TABLE TB_BACKUP_FUNC(
	ID INT,
	NM_NOME VARCHAR(100),
	DT_NASC DATE,
	NM_CPF VARCHAR(14),
	NM_RG VARCHAR(12),
	IC_SEXO CHAR(1),
	DT_EXCLUSAO DATETIME
);
