SELECT A.NM_NOME,B.CD_CEP,B.NM_LOGRADOURO,B.CD_NUMERO,B.NM_BAIRRO,B.NM_CIDADE,B.NM_UF
FROM tb_dado_funcionario A
INNER JOIN tb_endereco B ON A.ID = B.ID_DADO_FUNCIONARIO;

SELECT B.ID, B.VL_VALOR_SAL, A.DT_CARGA_HORARIA, A.DT_ATRASOS
FROM TB_FOLHA_PONTO A
INNER JOIN TB_SALARIO B ON A.ID=B.ID_FOLHA_PONTO;

SELECT A.NM_NOME,B.DS_EXPERIENCIAS_PROFISSIONAIS
FROM TB_DADO_DO_CANDIDATO A
INNER JOIN TB_CURRICULO B ON A.ID = B.ID_DADO_DO_CANDIDATO;

SELECT A.NM_NOME,A.IC_SEXO,B.VL_VT,B.IC_POSSUI_VT,B.VL_VR,B.IC_POSSUI_VR,B.VL_AUX_MEDICO,B.IC_POSSUI_AUXM
FROM TB_DADO_FUNCIONARIO A
INNER JOIN TB_BENEFICIO B ON A.ID = B.ID_DADO_FUNCIONARIO;

SELECT A.NM_NOME,B.DS_MOTIVOS
FROM TB_DADO_DO_CANDIDATO A
INNER JOIN TB_STAND_BY B ON A.ID = B.ID_DADO_CANDIDATO;

SELECT A.NM_NOME, A.NM_PORTADOR_PCD, B.NM_CARGO
FROM TB_DADO_DO_FUNCIONARIO_PCD A
INNER JOIN TB_CONTRATO B ON A.ID = B.ID_DADO_DO_FUNCIONARIO_PCD;

SELECT A.NM_NOME, A.IC_SEXO, B.DS_FISCALIZACAO
FROM TB_DADO_FUNCIONARIO A
INNER JOIN TB_PRESTACAO_CONTAS_FUNCIONARIO B ON A.ID = B.ID_DADO_FUNCIONARIO;

SELECT B.DT_RETORNO, A.NM_CARGO
FROM TB_CONTRATO A
INNER JOIN TB_FERIAS B ON A.ID = B.ID_CONTRATO;