CREATE OR REPLACE TRIGGER TG_DATA
BEFORE INSERT 
ON TB_DEMISSAO
FOR EACH ROW
SET
	NEW.DT_DEMISSAO = NOW();

CREATE OR REPLACE TRIGGER TG_UPDATE
BEFORE INSERT 
ON TB_CURRICULO
FOR EACH ROW
SET
	NEW.DT_ENVIO = NOW();
    
CREATE OR REPLACE TRIGGER TG_DELETE
AFTER DELETE ON TB_DADO_FUNCIONARIO
FOR EACH ROW
	INSERT INTO TB_BACKUP_FUNC (ID,NM_NOME, DT_NASC, NM_CPF, NM_RG, IC_SEXO)
	VALUES (OLD.ID,OLD.NM_NOME, OLD.DT_NASC, OLD.NM_CPF, OLD.NM_RG, OLD.IC_SEXO);
    
    
CREATE TRIGGER TG_DATA_EXCLUSAO
BEFORE INSERT ON TB_BACKUP_FUNC
FOR EACH ROW
SET
	NEW.DT_EXCLUSAO = NOW();