CREATE VIEW consulta_endereco AS
SELECT A.NM_NOME,B.CD_CEP,B.NM_LOGRADOURO,B.CD_NUMERO,B.NM_BAIRRO,B.NM_CIDADE,B.NM_UF
FROM tb_dado_funcionario A
INNER JOIN tb_endereco B ON A.ID = B.ID_DADO_FUNCIONARIO;

SELECT * FROM consulta_endereco;

CREATE VIEW consulta_folha AS
SELECT B.ID, B.VL_VALOR_SAL, A.DT_CARGA_HORARIA, A.DT_ATRASOS
FROM TB_FOLHA_PONTO A
INNER JOIN TB_SALARIO B ON A.ID=B.ID_FOLHA_PONTO;

SELECT * FROM consulta_folha;

CREATE VIEW consulta_experiencia AS
SELECT A.NM_NOME,B.DS_EXPERIENCIAS_PROFISSIONAIS
FROM TB_DADO_DO_CANDIDATO A
INNER JOIN TB_CURRICULO B ON A.ID = B.ID_DADO_DO_CANDIDATO;

SELECT * FROM consulta_experiencia;

CREATE VIEW consulta_dados AS
SELECT A.NM_NOME,A.IC_SEXO,B.VL_VT,B.IC_POSSUI_VT,B.VL_VR,B.IC_POSSUI_VR,B.VL_AUX_MEDICO,B.IC_POSSUI_AUXM
FROM TB_DADO_FUNCIONARIO A
INNER JOIN TB_BENEFICIO B ON A.ID = B.ID_DADO_FUNCIONARIO;

SELECT * FROM consulta_dados;